kind: pipeline
name: default
type: docker

workspace:
  base: /go
  path: src/github.com/nytimes/gizmo


steps:
  - name: tests
    image: "golang:1.14"
    pull: always
    environment:
      GO111MODULE: on
      GOPROXY: https://proxy.golang.org
    commands:
      - make test
#      - make staticcheck     # disabling staticcheck for now, too many open issues to fix before we can enable this
    when:
      event:
        - pull_request
        - push

