language: go
go: 
 - "1.11.x"
install: true

before_install:
  # Decrypts a script that installs an authenticated cookie
  # for git to use when cloning from googlesource.com.
  # Bypasses "bandwidth limit exceeded" errors.
  # See github.com/golang/go/issues/12933
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_83935ad6c1b7_key -iv $encrypted_83935ad6c1b7_iv -in gitcookies.sh.enc -out gitcookies.sh -d; fi
  - cd /tmp; go get github.com/axw/gocov/gocov
  - cd /tmp; go get github.com/mattn/goveralls
  - cd /tmp; go get golang.org/x/tools/cmd/cover

env:
  - GO111MODULE=on

install:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash gitcookies.sh; fi

script:
  - make test
  - make coverage

go:
  - "1.11.x"
