language: go

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

install:
  - mkdir -p "$GOPATH/src/github.com"
  - mv "$TRAVIS_BUILD_DIR" "$GOPATH/src/github.com/nytimes"

script:
  - make test
  - make coverage

go:
  - 1.4.2
  - 1.5.2
